### ISSUE TITLE
Remove rsvp dependency

### ISSUE THREAD

**Issue by ArtskydJ** [joliss/promise-map-series#6]
`promise-map-series` is tied to `rsvp`.

I would rather have `promise-map-series` presume that `Promise` is on scope, than to have it include another polyfill. I don't want every promise-related dependency to include their own polyfill.

Does this sound reasonable?

**Comment by joliss** [comment]
At the moment, some people want Node 0.10 compatibility, which doesn't have the ES6 `Promise` class yet. But I think we may be able to drop the RSVP dependency in the future, once we drop Node 0.10 support.

Another consideration is that RSVP supports `promise.finally()`, whereas ES6 doesn't. Though I think that's acceptable.

**Comment by RangerMauve** [comment]
Use `any-promise` instead

**Comment by ArtskydJ** [comment]
@RangerMauve, the problem I see is that almost every module that has a promise interface includes a promise polyfill. Ideally the application would include a polyfill if they want to support ES5, and none of the modules would include their own polyfills as well. Otherwise I can end up installing `promise`, `bluebird`, `rsvp`, `pinkie-promise`, and `native-promise-only` when I want to install only 0 or 1 of those.

**Comment by RangerMauve** [comment]
Well, `any-promise` uses Native by default or can use a polyfill that's defined at the top level rather than inside a module. That way module authors can leave it up to users to use whatever polyfills they want.

**Comment by joliss** [comment]
`any-promise` will break if the application forgets to depend on `rsvp` or `bluebird`. This is not good.

There's nothing wrong with having multiple promise libraries in the same application -- they work together fine.

Let's stick with the RSVP dependency until we drop Node 0.10 support.

**Comment by ArtskydJ** [comment]
> they work together fine

But each promise lib adds a bit of size to browser bundles. :stuck_out_tongue_winking_eye: 

> Let's stick with the RSVP dependency until we drop Node 0.10 support.

:+1: That's reasonable :grinning:
